trigger:
- main

pool:
  vmImage: 'windows-latest'

jobs:
- job: Build
  pool:
    vmImage: 'windows-latest'
  steps:
    - script: echo "Hello, approval please"
      displayName: 'Initial Greeting'

- job: Approval
  dependsOn: Build
  pool: server
  steps:
    - task: ManualValidation@0
      inputs:
        instructions: 'Please approve to proceed to the next step.'
        notifyUsers: krajashekar.reddy@cognizant.com
        onTimeout: 'reject'
      displayName: 'Approval Gate'

- job: Deploy
  dependsOn: Approval
  pool:
    vmImage: 'windows-latest'
  steps:
    - script: echo "Hi, welcome to IICS"
      displayName: 'Final Greeting'