trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  from_branch: ''
  to_branch: ''
  commit_hash: ''
  iics_username: ''
  iics_password: ''

jobs:
- job: cherry_pick
  displayName: 'Cherry Pick Commit on GitHub-Hosted Windows'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      git config --global user.name '2320618_DEV'
      git config --global user.email 'rajashekar.reddy@cognizant.com'
    displayName: 'Configure Git User'

  - script: |
      git fetch origin $(from_branch):$(from_branch)
    displayName: 'Fetch Source Branch'

  - script: |
      git checkout $(from_branch)
    displayName: 'Checkout Source Branch'

  - script: |
      git checkout $(to_branch)
      git cherry-pick --strategy=recursive -X theirs $(commit_hash)
    displayName: 'Cherry-pick Commit with Recursive Strategy and -X theirs'

  - script: |
      echo "scripts/" >> .gitignore
    displayName: 'Temporarily Ignore Scripts Folder'

  - script: |
      git add .
      git commit -m "Cherry-pick commit $(commit_hash)"
      git push origin $(to_branch)
    displayName: 'Push Changes to Remote'
